<section>
    <h2>Créer un nouveau Massif</h2>
    
    <?php if(isset($_GET['message'])):?>
        <p class=<?=htmlspecialchars($_GET['class'])?> ><?=htmlspecialchars($_GET['message'])?></p>
    <?php endif; ?>

    <form class="form" action="" method="POST" enctype="multipart/form-data">

        <div>
            <label for="massif_name">Nom du massif</label>
            <input type="text" name="massif_name" id="massif_name" placeholder="nom du massif">
        </div>

        <div>
            <label for="massif_description">Description du massif</label>
            <textarea name="massif_description" id="massif_description"></textarea>
        </div>

        <div class="form-btn-container">
            <button type="submit">Valider</button>
            <button type="reset">Effacer</button>
        </div>

    </form>
</section>