<!-- prtotection du template admin : si admin non connecté on redirige vers index -->
<?php
    if(!$this->connect->isAdmin()){
        header('location:index.php');
        exit();
    }
?>

<section>
    <h2>Modifier un Massif</h2>
    
    <?php if(isset($_GET['message'])):?>
        <p class=<?=htmlspecialchars($_GET['class'])?> ><?=htmlspecialchars($_GET['message'])?></p>
    <?php endif; ?>

    <form class="form" action="index.php?action=update_massif" method="POST" enctype="multipart/form-data">

        <div>
            <label for="massif_name">Nom du massif</label>
            <input type="text" name="massif_name" id="massif_name" placeholder="nom du massif" value="<?= htmlspecialchars($oneMassif['nom_massif']) ?>">
        </div>

        <div>
            <label for="massif_description">Présentation du massif</label>
            <textarea name="massif_description" id="massif_description"><?= htmlspecialchars($oneMassif['introduction']) ?></textarea>
        </div>

        <div class="form-btn-container">
            <button type="submit">Valider</button>
            <button type="reset">Effacer</button>
        </div>

    </form>
</section>