<section>
    <header class="header-walk">
    
        <div class="header-walk-img-container">
            <img  src="www/img/ballades/<?=htmlspecialchars($detailsWalk['photo'])?>" alt="photo de la randonnée">
            <div class="overlay"></div>
        </div>
        <div class="header-walk-title">
            <p><?=htmlspecialchars($detailsWalk['ville_depart'])?></p>
            <h2 class="header-walk-h2"><?=htmlspecialchars($detailsWalk['nom_rando'])?></h2>
        </div>
    </header>

    <ul class="header-walk-stat">
        <li>
            <i class="fa-solid fa-stopwatch"></i>
            <p class="">Durée</p>
            <p class=""><?=htmlspecialchars($detailsWalk['duree'])?></p>
        </li>
        <li>
            <i class="fa-solid fa-shoe-prints"></i>
            <p class="">Distance</p>
            <p class=""><?=htmlspecialchars($detailsWalk['distance']).' km'?></p>
        </li>
        <li>
            <i class="fa-solid fa-mountain"></i>
            <p class="">Dénivelé</p>
            <p class=""><?=htmlspecialchars($detailsWalk['denivele']).' m'?></p>
        </li>
        <li>
            <i class="fa-solid fa-fire-flame-curved"></i>
            <p class="">Calories</p>
            <p class=""><?=htmlspecialchars($detailsWalk['calories'])?></p>
        </li>
    </ul>

    <article>
        <h2 class="h2-main">La ballade</h2>
        <div class="walk-article">
            <img  src="www/img/ballades/<?=htmlspecialchars($detailsWalk['photo'])?>" alt="photo de la randonnée">
            <p>Ballade du <?=htmlspecialchars($detailsWalk['dateformat'])?></p>
            <p><?=htmlspecialchars($detailsWalk['resume'])?></p>
        </div>
    </article>

    <aside class="aside">
        <h2 class="h2-main">A propos </h2>
        <div class="aside-walk">
            <div class="map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d32278.804286964692!2d<?=htmlspecialchars($detailsWalk['lat'])?>!3d<?=htmlspecialchars($detailsWalk['longi'])?>!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sfr!2sfr!4v1647721608733!5m2!1sfr!2sfr"  allowfullscreen="" loading="lazy"></iframe>
            </div>
            <div class="massif-resume">
                <h3 class="h3-main">Le massif : <?=htmlspecialchars($detailsWalk['nom_massif'])?></h3>
                <p><?=htmlspecialchars($detailsWalk['introduction'])?></p>
            </div>
        </div>
    </aside>
</section>

<section class="section-style">
    <h2 class="h2-main">Historique de la Randonnée</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Départ</th>
                <th>Durée</th>
                <th>Distance</th>
                <th>Dénivelé</th>
                <th>Voir</th>
            </tr>
        </thead>
        
        <?php foreach($historicWalk as $item): ?>
        <tr>
            <td data-label="Date"><?=htmlspecialchars($item['dateformat'])?></td>
            <td data-label="départ"><?=htmlspecialchars($item['ville_depart'])?></td>
            <td data-label="Durée"><?=htmlspecialchars($item['duree'])?></td>
            <td data-label="Distance"><?=htmlspecialchars($item['distance'])?></td>
            <td data-label="Dénivelé"><?=htmlspecialchars($item['denivele'])?></td>
            <td data-label="Voir"><a href="index.php?action=walk_resume&id_walk=<?=htmlspecialchars($item['id_rando'])?>"><i class="fa-solid fa-eye"></i></a></td>
        </tr>
        <?php endforeach; ?>
    </table>
</section>